name: GPU

on:
  workflow_call:
    inputs:
      test_type:
        description: 'Type of tests to execute (unit, func, or rope)'
        type: string
        required: true
      device:
        description: 'Device name (igpu or dgpu)'
        type: string
        required: true
      runner:
        description: 'Runner labels by which the runner will be chosen. Example: [ "self-hosted", "igpu" ]'
        type: string
        required: true
      runner-group:
        description: 'Runner group from which the runner will be chosen'
        type: string
        required: true
      image:
        description: 'Docker image in which the tests would run'
        type: string
        required: false
        default: null
      options:
        description: 'Docker options to use for the job'
        type: string
        required: false
        default: ''

permissions: read-all

jobs:
  GPU:
    timeout-minutes: ${{ inputs.test_type == 'rope' && 60 || 80 }}
    runs-on:
      group: ${{ inputs.runner-group }}
      labels: ${{ fromJSON(inputs.runner) }}
    container:
      image: ${{ inputs.image }}
      volumes:
        - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates:ro # Needed to access CA certificates
        - /mount:/mount # Needed for HuggingFace model cache (RoPE tests)
        - ${{ github.workspace }}:${{ github.workspace }} # Needed as ${{ github.workspace }} is not working correctly when using Docker
      options: ${{ inputs.options }}
    defaults:
      run:
        shell: bash
    env:
      DEBIAN_FRONTEND: noninteractive # to prevent apt-get from waiting user input
      INSTALL_DIR: ${{ github.workspace }}/install
      INSTALL_TEST_DIR: ${{ github.workspace }}/install/tests
      GTEST_PARALLEL_SCRIPT: ${{ github.workspace }}/gtest_parallel.py
      MODEL_HUB_TESTS_INSTALL_DIR: ${{ github.workspace }}/install/tests/model_hub_tests
      NODE_EXTRA_CA_CERTS: /usr/local/share/ca-certificates/IntelProxyRootCA-Base64.crt
      REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt
      PIP_CERT: /etc/ssl/certs/ca-certificates.crt
      SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
      HF_HUB_CACHE: /mount/caches/huggingface
      USE_SYSTEM_CACHE: False
    steps:
      - name: Fetch setup_python and install wheels actions
        if: ${{ inputs.test_type == 'rope' }}
        uses: ababushk/checkout@9bec46a94a83db82acd4303e7627d88db71402a5 # cherry_pick_retries
        timeout-minutes: 15
        with:
          sparse-checkout: |
            .github/actions
          sparse-checkout-cone-mode: false
          submodules: 'false'

      - name: Download OpenVINO artifacts (wheels)
        if: ${{ inputs.test_type == 'rope' }}
        uses: akashchi/download-artifact@d59a9c15fec3fdb7c9adf09464124d00f9c11415
        with:
          name: openvino_wheels
          path: ${{ env.INSTALL_DIR }}

      - name: Download OpenVINO artifacts (package)
        uses: akashchi/download-artifact@d59a9c15fec3fdb7c9adf09464124d00f9c11415
        with:
          name: openvino_package
          path: ${{ env.INSTALL_DIR }}

      - name: Download OpenVINO artifacts (tests)
        uses: akashchi/download-artifact@d59a9c15fec3fdb7c9adf09464124d00f9c11415
        with:
          name: openvino_tests
          path: ${{ env.INSTALL_DIR }}

      - name: Download OpenVINO artifacts (tokenizers_wheel)
        if: ${{ inputs.test_type == 'rope' }}
        uses: akashchi/download-artifact@d59a9c15fec3fdb7c9adf09464124d00f9c11415
        with:
          name: openvino_tokenizers_wheel
          path: ${{ env.INSTALL_DIR }}

      - name: Extract OpenVINO packages
        run: |
            apt-get update && apt-get install -y pigz
            pigz -dc openvino_package.tar.gz | tar -xf - -v
            pigz -dc openvino_tests.tar.gz | tar -xf - -v
        working-directory: ${{ env.INSTALL_DIR }}

      - name: Install dependencies (Linux)
        run: |
          $INSTALL_DIR/install_dependencies/install_openvino_dependencies.sh -c=core -c=dev -c=gpu -y
          apt-get update && apt-get install -y wget software-properties-common ca-certificates gpg-agent tzdata clinfo
        env:
          DEBIAN_FRONTEND: noninteractive # to prevent apt-get from waiting user input
          TZ: "Europe/London" # to prevent tzdata from waiting user input

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        if: ${{ inputs.test_type != 'rope' }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup Python 3.11
        if: ${{ inputs.test_type == 'rope' }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.11.9'

      - name: Get gtest-parallel script
        if: ${{ inputs.test_type != 'rope' }}
        run: wget https://raw.githubusercontent.com/google/gtest-parallel/master/gtest_parallel.py

      - name: Install compute runtime drivers
        run: |
          wget https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.15985.7/intel-igc-core_1.0.15985.7_amd64.deb
          wget https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.15985.7/intel-igc-opencl_1.0.15985.7_amd64.deb
          wget https://github.com/intel/compute-runtime/releases/download/24.05.28454.6/intel-level-zero-gpu-dbgsym_1.3.28454.6_amd64.ddeb
          wget https://github.com/intel/compute-runtime/releases/download/24.05.28454.6/intel-level-zero-gpu_1.3.28454.6_amd64.deb
          wget https://github.com/intel/compute-runtime/releases/download/24.05.28454.6/intel-opencl-icd-dbgsym_24.05.28454.6_amd64.ddeb
          wget https://github.com/intel/compute-runtime/releases/download/24.05.28454.6/intel-opencl-icd_24.05.28454.6_amd64.deb
          wget https://github.com/intel/compute-runtime/releases/download/24.05.28454.6/libigdgmm12_22.3.11_amd64.deb
          dpkg -i *.deb

      - name: Install media & display runtimes
        if: ${{ inputs.device == 'dgpu' }}
        run: |
          apt-get update && apt-get install -y \
            libegl-mesa0 libegl1-mesa libegl1-mesa-dev libgbm1 libgl1-mesa-dev libgl1-mesa-dri \
            libglapi-mesa libgles2-mesa-dev libglx-mesa0 libxatracker2 mesa-va-drivers \
            mesa-vdpau-drivers mesa-vulkan-drivers va-driver-all
            wget -qO - https://repositories.intel.com/gpu/intel-graphics.key |  gpg --yes --dearmor --output /usr/share/keyrings/intel-graphics.gpg
            echo "deb [arch=amd64,i386 signed-by=/usr/share/keyrings/intel-graphics.gpg] https://repositories.intel.com/gpu/ubuntu jammy unified" | tee /etc/apt/sources.list.d/intel-gpu-jammy.list
            apt update
            apt-get install -y libze-intel-gpu1 libze1 intel-opencl-icd libze-dev intel-ocloc intel-level-zero-gpu-raytracing

      - name: Verify devices
        run: clinfo

      #
      # Tests
      #

      - name: Install OpenVINO Python wheels
        if: ${{ inputs.test_type == 'rope' }}
        uses: ./.github/actions/install_ov_wheels
        with:
          wheels-dir-path: ${{ env.INSTALL_DIR }}
          wheels-to-install: 'openvino openvino_tokenizers'

      - name: Install PyTorch tests requirements
        if: ${{ inputs.test_type == 'rope' }}
        run: |
          python3 -m pip install -r ${INSTALL_TEST_DIR}/requirements_pytorch

      - name: OpenVINO GPU ${{ inputs.test_type }} Tests
        if: ${{ inputs.test_type != 'rope' }}
        id: run_tests
        env:
          TEST_TYPE: ${{ inputs.test_type }}
          DEVICE: ${{ inputs.device }}
        run: |
          source ${INSTALL_DIR}/setupvars.sh

          TEST_RESULTS_DIR="${DEVICE}"_"${TEST_TYPE}"_tests
          echo "test_results_dir=$TEST_RESULTS_DIR" >> $GITHUB_OUTPUT

          rm -rf ${INSTALL_TEST_DIR}/${TEST_RESULTS_DIR} && mkdir -p ${INSTALL_TEST_DIR}/${TEST_RESULTS_DIR}

          test_filter=''
          if [[ "${TEST_TYPE}" == "unit" ]]; then
            # Ticket: 138018
            test_filter='-*scatter_nd_update_gpu.dynamic_padded_output*:*border_gpu.basic_zero_input*:*bicubic_zeros_no_align_data1x1*:*bicubic_border_align_batches*:*bilinear_zeros_no_align_data1x1*:*non_zero_gpu.empty_input*:*mark_shape_of_subgraphs.concat_with_empty_tensor_inputs*:*concat_cpu_impl.dynamic_4d_f*:*border_gpu.basic_zero_input_dynamic*:*network_test.model_with_empty_input_is_not_dynamic*:*bicubic_zeros_align_data1x1*'
          else
            test_filter='*smoke*'
          fi
          python3 ${GTEST_PARALLEL_SCRIPT} ${INSTALL_TEST_DIR}/ov_gpu_"${TEST_TYPE}"_tests --dump_json_test_results=${INSTALL_TEST_DIR}/${TEST_RESULTS_DIR}/ov_gpu_"${TEST_TYPE}"_tests.json -- --report_unique_name --gtest_filter=$test_filter

      - name: GPU RoPE Transformation Tests
        if: ${{ inputs.test_type == 'rope' }}
        run: |
          export PYTHONPATH=${MODEL_HUB_TESTS_INSTALL_DIR}:$PYTHONPATH
          python3 -m pip install optimum-intel transformers diffusers torch --upgrade --extra-index-url https://download.pytorch.org/whl/cpu
          python3 -m pytest ${MODEL_HUB_TESTS_INSTALL_DIR}/transformation_tests/test_transformations.py \
            -m precommit \
            --html=${INSTALL_TEST_DIR}/TEST-gpu_rope_tests.html \
            --self-contained-html -v --tb=short
        env:
          TEST_DEVICE: GPU

      - name: Upload Test Results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2 We are not using newest version v6.0.0 due to very frequent issues with 'Error: Unable to make request: ECONNRESET'
        if: ${{ inputs.test_type != 'rope' && !cancelled() }}
        with:
          name: test-results-${{ inputs.test_type }}-${{ inputs.device }}
          path: ${{ env.INSTALL_TEST_DIR }}/${{ steps.run_tests.outputs.test_results_dir }}
          if-no-files-found: 'error'

      - name: Upload Test Results (RoPE)
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: ${{ inputs.test_type == 'rope' && !cancelled() }}
        with:
          name: test-results-gpu-rope-${{ inputs.device }}
          path: |
            ${{ env.INSTALL_TEST_DIR }}/TEST-gpu*
          if-no-files-found: 'error'
