name: GPU RoPE Tests

on:
  workflow_call:
    inputs:
      device:
        description: 'GPU device type (igpu or dgpu)'
        type: string
        required: true
      runner:
        description: 'Runner labels by which the runner will be chosen. Example: [ "self-hosted", "igpu" ]'
        type: string
        required: true
      runner-group:
        description: 'Runner group from which the runner will be chosen'
        type: string
        required: true
      image:
        description: 'Docker image in which the tests would run'
        type: string
        required: false
        default: 'ubuntu:22.04'
      options:
        description: 'Docker options to use for the job'
        type: string
        required: false
        default: ''

permissions: read-all

env:
  HF_HUB_CACHE: /mount/caches/huggingface

jobs:
  GPU_RoPE_Tests:
    name: GPU RoPE Tests
    timeout-minutes: 60
    runs-on:
      group: ${{ inputs.runner-group }}
      labels: ${{ fromJSON(inputs.runner) }}
    container:
      image: ${{ inputs.image }}
      volumes:
        - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates:ro
        - /mount:/mount
        - ${{ github.workspace }}:${{ github.workspace }}
      options: ${{ inputs.options }}
    defaults:
      run:
        shell: bash
    env:
      DEBIAN_FRONTEND: noninteractive
      INSTALL_DIR: ${{ github.workspace }}/install
      INSTALL_TEST_DIR: ${{ github.workspace }}/install/tests
      MODEL_HUB_TESTS_INSTALL_DIR: ${{ github.workspace }}/install/tests/model_hub_tests
      USE_SYSTEM_CACHE: False
      NODE_EXTRA_CA_CERTS: /usr/local/share/ca-certificates/IntelProxyRootCA-Base64.crt
    steps:
      - name: Fetch setup_python and install wheels actions
        uses: ababushk/checkout@9bec46a94a83db82acd4303e7627d88db71402a5 # cherry_pick_retries
        timeout-minutes: 15
        with:
          sparse-checkout: |
            .github/actions
          sparse-checkout-cone-mode: false
          submodules: 'false'

      - name: Download OpenVINO artifacts (wheels)
        uses: akashchi/download-artifact@d59a9c15fec3fdb7c9adf09464124d00f9c11415
        with:
          name: openvino_wheels
          path: ${{ env.INSTALL_DIR }}

      - name: Download OpenVINO artifacts (tests)
        uses: akashchi/download-artifact@d59a9c15fec3fdb7c9adf09464124d00f9c11415
        with:
          name: openvino_tests
          path: ${{ env.INSTALL_DIR }}

      - name: Download OpenVINO artifacts (tokenizers_wheel)
        uses: akashchi/download-artifact@d59a9c15fec3fdb7c9adf09464124d00f9c11415
        with:
          name: openvino_tokenizers_wheel
          path: ${{ env.INSTALL_DIR }}

      - name: Download OpenVINO artifacts (package)
        uses: akashchi/download-artifact@d59a9c15fec3fdb7c9adf09464124d00f9c11415
        with:
          name: openvino_package
          path: ${{ env.INSTALL_DIR }}

      - name: Extract OpenVINO artifacts
        run: |
          apt-get update && apt-get install -y pigz
          pigz -dc openvino_package.tar.gz | tar -xf - -v
          pigz -dc openvino_tests.tar.gz | tar -xf - -v
        working-directory: ${{ env.INSTALL_DIR }}

      - name: Install dependencies
        run: |
          $INSTALL_DIR/install_dependencies/install_openvino_dependencies.sh -c=core -c=dev -c=gpu -y
          apt-get update && apt-get install -y wget software-properties-common ca-certificates gpg-agent tzdata clinfo
        env:
          DEBIAN_FRONTEND: noninteractive
          TZ: "Europe/London"

      - name: Install compute runtime drivers
        run: |
          wget https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.15985.7/intel-igc-core_1.0.15985.7_amd64.deb
          wget https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.15985.7/intel-igc-opencl_1.0.15985.7_amd64.deb
          wget https://github.com/intel/compute-runtime/releases/download/24.05.28454.6/intel-level-zero-gpu-dbgsym_1.3.28454.6_amd64.ddeb
          wget https://github.com/intel/compute-runtime/releases/download/24.05.28454.6/intel-level-zero-gpu_1.3.28454.6_amd64.deb
          wget https://github.com/intel/compute-runtime/releases/download/24.05.28454.6/intel-opencl-icd-dbgsym_24.05.28454.6_amd64.ddeb
          wget https://github.com/intel/compute-runtime/releases/download/24.05.28454.6/intel-opencl-icd_24.05.28454.6_amd64.deb
          wget https://github.com/intel/compute-runtime/releases/download/24.05.28454.6/libigdgmm12_22.3.11_amd64.deb
          dpkg -i *.deb

      - name: Install media & display runtimes
        if: ${{ inputs.device == 'dgpu' }}
        run: |
          apt-get update && apt-get install -y \
            libegl-mesa0 libegl1-mesa libegl1-mesa-dev libgbm1 libgl1-mesa-dev libgl1-mesa-dri \
            libglapi-mesa libgles2-mesa-dev libglx-mesa0 libxatracker2 mesa-va-drivers \
            mesa-vdpau-drivers mesa-vulkan-drivers va-driver-all
            wget -qO - https://repositories.intel.com/gpu/intel-graphics.key |  gpg --yes --dearmor --output /usr/share/keyrings/intel-graphics.gpg
            echo "deb [arch=amd64,i386 signed-by=/usr/share/keyrings/intel-graphics.gpg] https://repositories.intel.com/gpu/ubuntu jammy unified" | tee /etc/apt/sources.list.d/intel-gpu-jammy.list
            apt update
            apt-get install -y libze-intel-gpu1 libze1 intel-opencl-icd libze-dev intel-ocloc intel-level-zero-gpu-raytracing

      - name: Verify GPU devices
        run: clinfo

      - name: Setup Python 3.11
        uses: ./.github/actions/setup_python
        with:
          version: '3.11'
          should-setup-pip-paths: 'false'
          self-hosted-runner: 'true'

      - name: Install OpenVINO Python wheels
        uses: ./.github/actions/install_ov_wheels
        with:
          wheels-dir-path: ${{ env.INSTALL_DIR }}
          wheels-to-install: 'openvino openvino_tokenizers'

      - name: Install PyTorch tests requirements
        run: |
          python3 -m pip install -r ${INSTALL_TEST_DIR}/requirements_pytorch

      - name: GPU RoPE Transformation Tests
        run: |
          export PYTHONPATH=${MODEL_HUB_TESTS_INSTALL_DIR}:$PYTHONPATH
          python3 -m pip install optimum-intel transformers diffusers torch --upgrade --extra-index-url https://download.pytorch.org/whl/cpu
          python3 -m pytest ${MODEL_HUB_TESTS_INSTALL_DIR}/transformation_tests/test_transformations.py \
            -m precommit \
            --html=${INSTALL_TEST_DIR}/TEST-gpu_rope_tests.html \
            --self-contained-html -v --tb=short
        env:
          TEST_DEVICE: GPU

      - name: Upload Test Results
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        if: ${{ !cancelled() }}
        with:
          name: test-results-gpu-rope-${{ inputs.device }}
          path: |
            ${{ env.INSTALL_TEST_DIR }}/TEST-gpu*
          if-no-files-found: 'error'
